version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-challenges"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6rgq5404p7p"
s3_prefix = "crypto-challenges"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["hashChallengeFunction=384078725812.dkr.ecr.eu-west-1.amazonaws.com/cryptochallenges5f80f56e/hashchallengefunction9f056fafrepo"]
